APP_STL := gnustl_static

APP_CPPFLAGS := -frtti -std=c++11 -fsigned-char
APP_LDFLAGS := -latomic

APP_CPPFLAGS += -DCC_ENABLE_CHIPMUNK_INTEGRATION=0
APP_CPPFLAGS += -DCC_USE_PHYSICS=0
APP_CPPFLAGS += -DCC_USE_3D_PHYSICS=0
APP_CPPFLAGS += -DCC_USE_NAVMESH=0
APP_CPPFLAGS += -DCC_ENABLE_SCRIPT_BINDING=0
APP_CPPFLAGS += -DCC_USE_JPEG=0
APP_CPPFLAGS += -DCC_USE_TIFF=0
APP_CPPFLAGS += -DCC_USE_WEBP=0
APP_CPPFLAGS += -DCC_FIX_ARTIFACTS_BY_STRECHING_TEXEL=1

ifeq ($(NDK_DEBUG),1)
  APP_CPPFLAGS += -DCOCOS2D_DEBUG=1
  APP_OPTIM := debug
else
  APP_CPPFLAGS += -DNDEBUG
  APP_OPTIM := release
endif
